name: chemical_engineering_calculator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0

  # DartX
  dartx: ^1.1.0

  # Math Parser for calculations
  math_parser: ^1.5.1

  # Inset Box Shadow
  flutter_inset_box_shadow: ^1.0.8

  # Internationalization
  intl: ^0.18.0
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # dart_code_metrics: ^5.1.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Avara
      fonts:
        - asset: assets/fonts/AvaraBlack.otf
        - asset: assets/fonts/AvaraBold.otf
          weight: 700
        - asset: assets/fonts/AvaraBoldItalic.otf
          style: italic
